[window]
opacity = 0.95
decorations = "full"

[window.padding]
x = 0
y = 0

[font]
size = 17.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors]

[colors.primary]
background = '0x1d2021'
foreground = '0xd4be98'

[colors.normal]
black = '0x32302f'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'

[colors.bright]
black = '0x32302f'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'

[colors.cursor]
cursor = '0x89b482'
# cursor = '0xec5d2a'
